info:
  title: Rainfall Prediction API
  description: This API predicts rainfall based on weather data.
  version: 1.0.0
paths:
  "/predict":
    post:
      tags:
      - predictions
      summary: Predict
      description: |-
        Create a new rainfall prediction based on weather data.
        - **temperature**: Temperature in Celsius
        - **humidity**: Humidity percentage
        - **wind_speed**: Wind speed in km/h
      operationId: predict_predict_post
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/WeatherData"
        required: true
      responses:
        '201':
          description: Successful Response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Prediction"
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
  "/predict/{prediction_id}":
    get:
      tags:
      - predictions
      summary: Get Prediction
      description: |-
        Retrieve a specific rainfall prediction by its ID.
        - **prediction_id**: The ID of the prediction to retrieve
        - **unit**: Optional unit for rainfall measurement (mm or inches)
      operationId: get_prediction_predict__prediction_id__get
      parameters:
      - required: true
        schema:
          title: The ID of the prediction to retrieve
          type: integer
        name: prediction_id
        in: path
      - description: Unit for rainfall measurement
        required: false
        schema:
          allOf:
          - "$ref": "#/components/schemas/Unit"
          description: Unit for rainfall measurement
        name: unit
        in: query
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Prediction"
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
    put:
      tags:
      - predictions
      summary: Update Prediction
      description: |-
        Update an existing rainfall prediction.
        - **prediction_id**: The ID of the prediction to update
        - **rainfall**: The new rainfall value in mm
      operationId: update_prediction_predict__prediction_id__put
      parameters:
      - required: true
        schema:
          title: The ID of the prediction to update
          type: integer
        name: prediction_id
        in: path
      requestBody:
        content:
          application/json:
            schema:
              title: Update
              allOf:
              - "$ref": "#/components/schemas/PredictionUpdate"
              description: Updated rainfall value
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Prediction"
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
    delete:
      tags:
      - predictions
      summary: Delete Prediction
      description: |-
        Delete a specific rainfall prediction.
        - **prediction_id**: The ID of the prediction to delete
      operationId: delete_prediction_predict__prediction_id__delete
      parameters:
      - required: true
        schema:
          title: The ID of the prediction to delete
          type: integer
        name: prediction_id
        in: path
      responses:
        '204':
          description: Successful Response
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
  "/predictions":
    get:
      tags:
      - predictions
      summary: List Predictions
      description: |-
        List all rainfall predictions with pagination.
        - **skip**: Number of predictions to skip (for pagination)
        - **limit**: Maximum number of predictions to return (for pagination)
      operationId: list_predictions_predictions_get
      parameters:
      - description: Number of predictions to skip
        required: false
        schema:
          title: Skip
          minimum: 0
          type: integer
          description: Number of predictions to skip
          default: 0
        name: skip
        in: query
      - description: Maximum number of predictions to return
        required: false
        schema:
          title: Limit
          maximum: 100
          minimum: 1
          type: integer
          description: Maximum number of predictions to return
          default: 10
        name: limit
        in: query
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                title: Response List Predictions Predictions Get
                type: array
                items:
                  "$ref": "#/components/schemas/Prediction"
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
components:
  schemas:
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            "$ref": "#/components/schemas/ValidationError"
    Prediction:
      title: Prediction
      required:
      - id
      - rainfall
      - unit
      type: object
      properties:
        id:
          title: Id
          type: integer
        rainfall:
          title: Rainfall
          type: number
        unit:
          title: Unit
          type: string
    PredictionUpdate:
      title: PredictionUpdate
      required:
      - rainfall
      type: object
      properties:
        rainfall:
          title: Rainfall
          minimum: 0
          type: number
          description: Updated rainfall prediction in mm
    Unit:
      title: Unit
      enum:
      - mm
      - inches
      type: string
      description: An enumeration.
    ValidationError:
      title: ValidationError
      required:
      - loc
      - msg
      - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            anyOf:
            - type: string
            - type: integer
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
    WeatherData:
      title: WeatherData
      required:
      - temperature
      - humidity
      - wind_speed
      type: object
      properties:
        temperature:
          title: Temperature
          exclusiveMaximum: 60
          exclusiveMinimum: -50
          type: number
          description: Temperature in Celsius
        humidity:
          title: Humidity
          maximum: 100
          minimum: 0
          type: number
          description: Humidity percentage
        wind_speed:
          title: Wind Speed
          minimum: 0
          type: number
          description: Wind speed in km/h
      example:
        temperature: 25.5
        humidity: 60
        wind_speed: 10.3
tags:
- name: predictions
  description: Operations with rainfall predictions
